# run main.go file
name: Run main.go file
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Run main.go file
        run: go run .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # commit the changes to the repository
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "scraped data"
          add: "go_data.csv"
          # pull and merge the changes to the repository
      # - name: Pull and merge changes
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     author_name: ${{ github.actor }}
      #     author_email: ${{ github.actor }}@users.noreply.github.com
      #     message: "scraped data"
      #     add: "go_data.csv"
      #     pull_strategy: "merge"

      #     # push the changes to the repository

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
